[package]
name = "rust_waterkit"
version = "0.1.1"
edition = "2021"

[lib]
name = "rust_waterkit"
crate-type = ["cdylib", "lib"]

[dependencies]
bytemuck = "1.23.1"
cubecl = { version = "0.6.0", features = ["wgpu"]}
cubecl-random = "0.6.0"
fixed = "1.28.0"
itertools = "0.14.0"
kdtree = "0.7.0"
kiddo = "5.0.3"
lazy_static = "1.5.0"
log = "0.4.25"
nalgebra = "0.32.3"
ncollide3d = "0.33.0"
ndarray = "0.16.1"
plotters = "0.3.7"
pyo3 = "0.23.4"
rand = "0.8.5"
rayon = "1.10.0"
rstar = "0.12.2"
simple-logging = "2.0.2"

[features]
default = ["extension-module", "cuda", "tip3p", "gcmc"]
extension-module = ["pyo3/extension-module"]
wgpu = ["cubecl/wgpu"]
cuda = ["cubecl/cuda"]
cpu = []
tip3p = []
tip3pfp = []
gcmc = []
mc_after_gcmc = []


# [profile.release]
# debug = true
