[package]
name = "rust_waterkit"
version = "0.1.1"
edition = "2021"

[lib]
name = "rust_waterkit"
crate-type = ["cdylib", "lib"]

[dependencies]
fixed = "1.28.0"
itertools = "0.14.0"
kdtree = "0.7.0"
kiddo = "5.0.3"
log = "0.4.25"
nalgebra = "0.33.2"
ndarray = "0.16.1"
pyo3 = "0.23.4"
rand = "0.8.5"
rayon = "1.10.0"
rstar = "0.12.2"
simple-logging = "2.0.2"

[features]
extension-module = ["pyo3/extension-module"]

[profile.release]
debug = true